import type { Fixture } from "./CatalogSection";

// Серия светильников Минивольт
import { catalogMinivoltPart1 } from "./catalogMinivoltPart1";

// Собираем все части (добавляйте новые части в этот массив при необходимости)
export const catalogMinivolt = [
  ...catalogMinivoltPart1,
  // Дальше все "К" исполнения для Консоль
  {
    id: 6,
    name: "Минивольт 40-67-5000-К-30-12-Консоль",
    category: "Консольное",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "К-30",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"К-30\"", "Напряжение питания, В": "12", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 7,
    name: "Минивольт 40-67-5000-К-12-12-Консоль",
    category: "Консольное",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "К-12",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"К-12\"", "Напряжение питания, В": "12", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  // ========== Скоба исполнение ==========
  {
    id: 8,
    name: "Минивольт 40-67-5000-Д-12-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 5480,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Д - 120°",
    warranty: 2,
    price: 7470,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 580 мм, W: 60 мм, H: 55 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Д\" - 120°", "Напряжение питания, В": "12", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 9,
    name: "Минивольт 40-67-5000-Д-24-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 5480,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Д - 120°",
    warranty: 2,
    price: 7470,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 580 мм, W: 60 мм, H: 55 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Д\" - 120°", "Напряжение питания, В": "24", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 10,
    name: "Минивольт 40-67-5000-Д-36-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 5480,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Д - 120°",
    warranty: 2,
    price: 7470,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 580 мм, W: 60 мм, H: 55 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Д\" - 120°", "Напряжение питания, В": "36", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 11,
    name: "Минивольт 40-67-5000-Ш-12-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Ш",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Ш\"", "Напряжение питания, В": "12", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 12,
    name: "Минивольт 40-67-5000-С-12-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "С - 90°",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"С- 90°\"", "Напряжение питания, В": "12", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 13,
    name: "Минивольт 40-67-5000-Г-12-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Г - 60°",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Г - 60°\"", "Напряжение питания, В": "12", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 14,
    name: "Минивольт 40-67-5000-К-30-12-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "К-30",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"К-30\"", "Напряжение питания, В": "12", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 15,
    name: "Минивольт 40-67-5000-К-12-12-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "К-12",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"К-12\"", "Напряжение питания, В": "12", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 16,
    name: "Минивольт 40-67-5000-Ш-24-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Ш",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Ш\"", "Напряжение питания, В": "24", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 17,
    name: "Минивольт 40-67-5000-С-24-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "С - 90°",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"С- 90°\"", "Напряжение питания, В": "24", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 18,
    name: "Минивольт 40-67-5000-Г-24-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Г - 60°",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Г - 60°\"", "Напряжение питания, В": "24", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 19,
    name: "Минивольт 40-67-5000-К-30-24-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "К-30",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"К-30\"", "Напряжение питания, В": "24", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 20,
    name: "Минивольт 40-67-5000-К-12-24-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "К-12",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"К-12\"", "Напряжение питания, В": "24", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 21,
    name: "Минивольт 40-67-5000-Ш-36-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Ш",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Ш\"", "Напряжение питания, В": "36", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 22,
    name: "Минивольт 40-67-5000-С-36-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "С - 90°",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"С- 90°\"", "Напряжение питания, В": "36", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 23,
    name: "Минивольт 40-67-5000-Г-36-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "Г - 60°",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"Г - 60°\"", "Напряжение питания, В": "36", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 24,
    name: "Минивольт 40-67-5000-К-30-36-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "К-30",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"К-30\"", "Напряжение питания, В": "36", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  },
  {
    id: 25,
    name: "Минивольт 40-67-5000-К-12-36-Скоба",
    category: "Скоба",
    power: 40,
    luminous_flux: 6000,
    ip_rating: "67",
    color_temperature: 5000,
    beam_angle: "К-12",
    warranty: 2,
    price: 15516,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 350 мм, W: 110 мм, H: 76 мм",
    availability: true,
    properties: { "I": "6", "P": "7", "КСС": "\"К-12\"", "Напряжение питания, В": "36", "Гарантия, лет": "2", "Рабочий диапазон температур": "от -40 до + 40 °C", "Светодиоды": "Lumileds" }
  }
];
