
import type { Fixture } from "./CatalogSection";

// Собираем все части каталога, аккуратно приводя к типу Fixture
export const catalogData: Fixture[] = [
  // Часть 2: Гармония и Буран
  {
    id: 234,
    name: "Гармония 34-20-5000-Д-220-универсальное",
    power: 34,
    luminous_flux: 4250,
    ip_rating: "20",
    color_temperature: 5000,
    category: "Универсальное",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 3418,
    material: "Сталь/микропризма",
    dimensions: "L: 595 мм, W: 595 мм, H: 40 мм",
    availability: true,
    properties: {
      "I": "2",
      "P": "0",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -20 до + 30 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 235,
    name: "Гармония 40-20-5000-Д-220-универсальное",
    power: 40,
    luminous_flux: 5400,
    ip_rating: "20",
    color_temperature: 5000,
    category: "Универсальное",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 3533,
    material: "Сталь/микропризма",
    dimensions: "L: 595 мм, W: 595 мм, H: 40 мм",
    availability: true,
    properties: {
      "I": "2",
      "P": "0",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -20 до + 30 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 256,
    name: "Буран 96-67-5000-Д-220-Консоль",
    power: 96,
    luminous_flux: 17396,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Консольное",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 10020,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 500 мм, W: 110 мм, H: 70 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -60 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 257,
    name: "Буран 144-67-5000-Д-220-Консоль",
    power: 144,
    luminous_flux: 26094,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Консольное",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 15036,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 750 мм, W: 110 мм, H: 70 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -60 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 258,
    name: "Буран 192-67-5000-Д-220-Консоль",
    power: 192,
    luminous_flux: 34792,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Консольное",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 20040,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 1000 мм, W: 110 мм, H: 70 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -60 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  // Часть 3: Буран
  {
    id: 1,
    name: "Буран 96-67-5000-Д-220-Консоль",
    power: 96,
    luminous_flux: 17396,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Консольное",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 10020,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 500 мм, W: 110 мм, H: 70 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -60 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 2,
    name: "Буран 144-67-5000-Д-220-Консоль",
    power: 144,
    luminous_flux: 26094,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Консольное",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 15036,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 750 мм, W: 110 мм, H: 70 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -60 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 3,
    name: "Буран 192-67-5000-Д-220-Консоль",
    power: 192,
    luminous_flux: 34792,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Консольное",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 20052,
    material: "Алюминий/прозрачный противоударный поликарбонат",
    dimensions: "L: 1000 мм, W: 110 мм, H: 70 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5", 
      "Рабочий диапазон температур": "от -60 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 4,
    name: "Буран 96-67-5000-Ш-220-Консоль",
    power: 96,
    luminous_flux: 16704,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Консольное",
    beam_angle: "Ш",
    warranty: 5,
    price: 18930,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 500 мм, W: 110 мм, H: 70 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Ш\"",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5", 
      "Рабочий диапазон температур": "от -60 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 5,
    name: "Буран 96-67-5000-С-220-Консоль",
    power: 96,
    luminous_flux: 16704,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Консольное",
    beam_angle: "С - 90°",
    warranty: 5,
    price: 18930,
    material: "Алюминий/оптика ППМА",
    dimensions: "L: 500 мм, W: 110 мм, H: 70 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"С\"- 90°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5", 
      "Рабочий диапазон температур": "от -60 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  // Часть 5: Бутик, Гранит
  {
    id: 300,
    name: "Бутик 24-54-5000-Д-220-подвес",
    power: 24,
    luminous_flux: 3000,
    ip_rating: "54",
    color_temperature: 5000,
    category: "Подвесы",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 4191,
    material: "Алюминий/матовый поликарбонат",
    dimensions: "L: 600 мм, W: 60 мм, H: 55 мм",
    availability: true,
    properties: {
      "I": "5",
      "P": "4",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -40 до + 40 °C",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 301,
    name: "Бутик 36-54-5000-Д-220-подвес",
    power: 36,
    luminous_flux: 4500,
    ip_rating: "54",
    color_temperature: 5000,
    category: "Подвесы",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 5365,
    material: "Алюминий/матовый поликарбонат",
    dimensions: "L: 900 мм, W: 60 мм, H: 55 мм",
    availability: true,
    properties: {
      "I": "5",
      "P": "4",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -40 до + 40 °C",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 302,
    name: "Бутик 48-54-5000-Д-220-подвес",
    power: 48,
    luminous_flux: 6000,
    ip_rating: "54",
    color_temperature: 5000,
    category: "Подвесы",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 6689,
    material: "Алюминий/матовый поликарбонат",
    dimensions: "L: 1200 мм, W: 60 мм, H: 55 мм",
    availability: true,
    properties: {
      "I": "5",
      "P": "4",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -40 до + 40 °C",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 144,
    name: "Гранит 40-67-5000-Д-220-Кронштейн",
    power: 40,
    luminous_flux: 5500,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Кронштейн",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 7272,
    material: "Алюминий/закаленное стекло",
    dimensions: "L: 380 мм, W: 265 мм, H: 100 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -50 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  },
  {
    id: 145,
    name: "Гранит 80-67-5000-Д-220-Кронштейн",
    power: 80,
    luminous_flux: 11000,
    ip_rating: "67",
    color_temperature: 5000,
    category: "Кронштейн",
    beam_angle: "Д - 120°",
    warranty: 5,
    price: 11616,
    material: "Алюминий/закаленное стекло",
    dimensions: "L: 460 мм, W: 305 мм, H: 100 мм",
    availability: true,
    properties: {
      "I": "6",
      "P": "7",
      "КСС": "\"Д\" - 120°",
      "Напряжение питания, В": "220",
      "Гарантия, лет": "5",
      "Рабочий диапазон температур": "от -50 до + 40 °С",
      "Светодиоды": "Lumileds"
    }
  }
];
